import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width >= 768;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: '#f5f5f5',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
    letterSpacing: 0.5,
  },
  headerAccent: {
    color: '#f7b638',
  },
  headerSub: {
    display: 'none',
  },
  newPlanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#f7b638',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  newPlanBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  tabletRow: {
    gap: 12,
    justifyContent: 'space-between',
  },
  content: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  statsSection: {
    marginBottom: 12,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 4,
  },
  statCardWrapper: {
    width: Math.floor((width - 24 - 12) / 3),
  },
  searchSection: {
    marginBottom: 12,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff9e6',
    borderRadius: 24,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1.5,
    borderColor: '#f7b638',
  },
  searchInput: {
    flex: 1,
    marginLeft: 6,
    fontSize: 12,
    color: '#1a1a1a',
    fontWeight: '500',
  },
  clearButton: {
    padding: 3,
    borderRadius: 12,
    backgroundColor: '#f7b638',
  },
  filterSection: {
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  planFilterContainer: {
    marginTop: 12,
  },
  filterLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 8,
    paddingHorizontal: 2,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  filterTab: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    backgroundColor: '#ffffff',
  },
  filterTabActive: {
    backgroundColor: '#f7b638',
    borderColor: '#f7b638',
  },
  filterText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6B7280',
    textTransform: 'capitalize',
  },
  filterTextActive: {
    color: '#1a1a1a',
    fontWeight: '700',
  },
  plansSection: {
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingHorizontal: 2,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  sectionSubtitle: {
    fontSize: 11,
    color: '#9CA3AF',
    fontWeight: '600',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  listContainer: {
    gap: 10,
    paddingBottom: 8,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: isTablet ? 100 : 80,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  emptyIcon: {
    marginBottom: 20,
    opacity: 0.4,
  },
  emptyText: {
    fontSize: isTablet ? 20 : 18,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  emptySubtext: {
    fontSize: 15,
    color: '#9CA3AF',
    textAlign: 'center',
    paddingHorizontal: 40,
    lineHeight: 22,
    fontWeight: '500',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F6F3',
  },
  loadingText: {
    marginTop: 20,
    fontSize: 16,
    color: '#6B7280',
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  skeletonCard: {
    backgroundColor: '#F9FAFB',
    overflow: 'hidden',
  },
  skeletonHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  skeletonIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#E5E7EB',
  },
  skeletonGrowth: {
    width: 40,
    height: 20,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
  },
  skeletonValue: {
    width: 60,
    height: 28,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
    marginBottom: 6,
  },
  skeletonTitle: {
    width: 80,
    height: 14,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
  },
  skeletonSearchIcon: {
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
  },
  skeletonSearchInput: {
    flex: 1,
    height: 16,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
    marginLeft: 12,
  },
});
