import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width >= 768;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F6F3',
  },
  header: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: isTablet ? 28 : 20,
    paddingVertical: isTablet ? 18 : 14,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#780115',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 8,
  },
  headerTitle: {
    fontSize: isTablet ? 24 : 20,
    fontWeight: '800',
    color: '#1A1A2E',
    letterSpacing: -0.5,
  },
  headerSub: {
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '500',
    marginTop: 1,
  },
  newPlanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#780115',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    shadowColor: '#780115',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  newPlanBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  tabletRow: {
    gap: 12,
    justifyContent: 'space-between',
  },
  content: {
    flex: 1,
    paddingHorizontal: isTablet ? 24 : 16,
    paddingTop: isTablet ? 22 : 18,
  },
  statsSection: {
    marginBottom: isTablet ? 36 : 32,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: isTablet ? 10 : 8,
    marginBottom: isTablet ? 8 : 4,
  },
  statCardWrapper: {
    width: isTablet
      ? Math.floor((width - 48 - 20) / 3)
      : Math.floor((width - 32 - 16) / 3),
  },
  searchSection: {
    marginBottom: isTablet ? 32 : 28,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: isTablet ? 14 : 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  searchInput: {
    flex: 1,
    marginLeft: 12,
    fontSize: isTablet ? 16 : 15,
    color: '#111827',
    fontWeight: '500',
  },
  clearButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#F3F4F6',
  },
  filterSection: {
    marginBottom: isTablet ? 36 : 32,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: isTablet ? 10 : 8,
  },
  planFilterContainer: {
    marginTop: isTablet ? 18 : 14,
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 12,
    paddingHorizontal: 2,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  filterTab: {
    paddingVertical: isTablet ? 10 : 7,
    paddingHorizontal: isTablet ? 18 : 12,
    borderRadius: 24,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E5E0D8',
    backgroundColor: '#FFFFFF',
  },
  filterTabActive: {
    backgroundColor: '#780115',
    borderColor: '#780115',
    shadowColor: '#780115',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 4,
  },
  filterText: {
    fontSize: isTablet ? 13 : 11,
    fontWeight: '600',
    color: '#6B7280',
    letterSpacing: 0.1,
    textTransform: 'capitalize',
  },
  filterTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  plansSection: {
    marginBottom: 36,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 2,
  },
  sectionTitle: {
    fontSize: isTablet ? 20 : 18,
    fontWeight: '800',
    color: '#1A1A2E',
    letterSpacing: -0.3,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '600',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  listContainer: {
    gap: 16,
    paddingBottom: isTablet ? 0 : 8,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: isTablet ? 100 : 80,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  emptyIcon: {
    marginBottom: 20,
    opacity: 0.4,
  },
  emptyText: {
    fontSize: isTablet ? 20 : 18,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  emptySubtext: {
    fontSize: 15,
    color: '#9CA3AF',
    textAlign: 'center',
    paddingHorizontal: 40,
    lineHeight: 22,
    fontWeight: '500',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F6F3',
  },
  loadingText: {
    marginTop: 20,
    fontSize: 16,
    color: '#6B7280',
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  skeletonCard: {
    backgroundColor: '#F9FAFB',
    overflow: 'hidden',
  },
  skeletonHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  skeletonIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#E5E7EB',
  },
  skeletonGrowth: {
    width: 40,
    height: 20,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
  },
  skeletonValue: {
    width: 60,
    height: 28,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
    marginBottom: 6,
  },
  skeletonTitle: {
    width: 80,
    height: 14,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
  },
  skeletonSearchIcon: {
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
  },
  skeletonSearchInput: {
    flex: 1,
    height: 16,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
    marginLeft: 12,
  },
});
