import { StyleSheet } from 'react-native';

export const subscriptionsStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    flexGrow: 1,
  },
  fixedHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#f5f5f5',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1a1a1a',
    letterSpacing: 1,
  },
  titleAccent: {
    color: '#f7b638',
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: '#f5f5f5',
  },
  subtitle: {
    fontSize: 14,
    color: '#64748B',
    lineHeight: 20,
  },
  currentPlanBanner: {
    backgroundColor: '#f7b638',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  bannerText: {
    gap: 2,
  },
  bannerTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1a1a1a',
    opacity: 0.8,
  },
  bannerPlan: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  bannerRight: {
    alignItems: 'flex-end',
    gap: 2,
  },
  bannerAmount: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  bannerDuration: {
    fontSize: 12,
    fontWeight: '500',
    color: '#1a1a1a',
    opacity: 0.8,
  },
  plansContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 16,
  },
  planCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  featuredCard: {
    borderColor: '#f7b638',
    shadowColor: '#f7b638',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  featuredBadge: {
    position: 'absolute',
    top: -12,
    right: 20,
    backgroundColor: '#f7b638',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  featuredBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#1a1a1a',
    letterSpacing: 0.5,
  },
  planHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  planName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  planDurationBadge: {
    backgroundColor: '#fff9e6',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  planDurationText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },
  planPriceSection: {
    marginBottom: 16,
  },
  planPrice: {
    fontSize: 36,
    fontWeight: '800',
    color: '#f7b638',
    marginBottom: 4,
  },
  planDescription: {
    fontSize: 14,
    color: '#64748B',
  },
  planFeatures: {
    gap: 8,
    marginBottom: 20,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  featureText: {
    fontSize: 14,
    color: '#475569',
  },
  selectButton: {
    backgroundColor: '#f5f5f5',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  featuredButton: {
    backgroundColor: '#f7b638',
  },
  selectButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  featuredButtonText: {
    color: '#1a1a1a',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 24,
  },
  footerText: {
    fontSize: 13,
    color: '#64748B',
  },
  errorContainer: {
    alignItems: 'center',
    padding: 40,
  },
  errorText: {
    marginTop: 12,
    color: '#EF4444',
    fontSize: 14,
  },
  retryButton: {
    marginTop: 16,
    padding: 12,
    backgroundColor: '#f7b638',
    borderRadius: 12,
    paddingHorizontal: 24,
  },
  retryButtonText: {
    color: '#1a1a1a',
    fontSize: 14,
    fontWeight: '600',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailHeader: {
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 20,
  },
  detailIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#fff9e6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  detailPlanName: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 8,
  },
  detailDurationBadge: {
    backgroundColor: '#f7b638',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
  },
  detailDurationText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  detailPriceCard: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginBottom: 24,
    padding: 24,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  detailPriceLabel: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 8,
  },
  detailPrice: {
    fontSize: 48,
    fontWeight: '800',
    color: '#f7b638',
    marginBottom: 8,
  },
  detailDescription: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
  },
  detailSection: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  detailSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 16,
  },
  detailFeatures: {
    gap: 12,
  },
  detailFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  detailFeatureText: {
    fontSize: 14,
    color: '#475569',
    flex: 1,
  },
  detailInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  detailInfoText: {
    fontSize: 14,
    color: '#475569',
    flex: 1,
  },
  purchaseButton: {
    backgroundColor: '#f7b638',
    marginHorizontal: 16,
    marginBottom: 24,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#f7b638',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  purchaseButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  purchaseButtonDisabled: {
    backgroundColor: '#d1d5db',
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  gatewayOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#f9f9f9',
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  gatewayOptionSelected: {
    borderColor: '#f7b638',
    backgroundColor: '#fff9e6',
  },
  gatewayLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  gatewayIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#00B9F1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  gatewayIconEsewa: {
    backgroundColor: '#60BB46',
  },
  gatewayIconText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  gatewayInfo: {
    gap: 2,
  },
  gatewayName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  gatewayDescription: {
    fontSize: 12,
    color: '#64748B',
  },
  gatewayRadio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#d1d5db',
    justifyContent: 'center',
    alignItems: 'center',
  },
  gatewayRadioSelected: {
    borderColor: '#f7b638',
  },
  gatewayRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#f7b638',
  },
});
