import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");
const isTablet = width >= 768;
const isDesktop = width >= 1024;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F6F3",
  },
  header: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: isTablet ? 28 : 20,
    paddingVertical: isTablet ? 22 : 18,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    alignItems: "center",
    shadowColor: "#780115",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 8,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: isTablet ? 26 : 22,
    fontWeight: "800",
    color: "#1A1A2E",
    textAlign: "center",
    letterSpacing: -0.5,
  },
  headerActions: {
    flexDirection: "row",
    gap: 12,
  },
  addButton: {
    backgroundColor: "#780115",
    borderRadius: 16,
    padding: isTablet ? 14 : 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: "#780115",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  addButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  content: {
    flex: 1,
    paddingHorizontal: isTablet ? 24 : 16,
    paddingTop: isTablet ? 22 : 18,
  },
  statsSection: {
    marginBottom: isTablet ? 36 : 32,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: isTablet ? 8 : 4,
  },
  statCardWrapper: {
    width: Math.floor((width - (isTablet ? 48 : 32) - 20) / 3),
  },
  searchSection: {
    marginBottom: isTablet ? 32 : 28,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: isTablet ? 14 : 12,
    marginBottom: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  searchInput: {
    flex: 1,
    marginLeft: 12,
    fontSize: isTablet ? 16 : 15,
    color: "#111827",
    fontWeight: "500",
  },
  clearButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
  },
  filterSection: {
    marginBottom: isTablet ? 36 : 32,
  },
  filterContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: isTablet ? 16 : 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#F0F0F0",
    position: "relative",
    overflow: "hidden",
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: isTablet ? 10 : 8,
  },
  planFilterContainer: {
    marginTop: isTablet ? 18 : 14,
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#374151",
    marginBottom: 12,
    paddingHorizontal: 2,
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  filterTab: {
    paddingVertical: isTablet ? 10 : 8,
    paddingHorizontal: isTablet ? 18 : 14,
    borderRadius: 24,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#E5E0D8",
    backgroundColor: "#FFFFFF",
  },
  filterTabActive: {
    backgroundColor: "#780115",
    borderColor: "#780115",
    shadowColor: "#780115",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 4,
  },
  filterText: {
    fontSize: isTablet ? 13 : 12,
    fontWeight: "600",
    color: "#6B7280",
    letterSpacing: 0.1,
    textTransform: "capitalize",
  },
  filterTextActive: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  salonsSection: {
    marginBottom: 36,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingHorizontal: 2,
  },
  sectionTitle: {
    fontSize: isTablet ? 20 : 18,
    fontWeight: "800",
    color: "#1A1A2E",
    letterSpacing: -0.3,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: "#9CA3AF",
    fontWeight: "600",
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  listContainer: {
    gap: 14,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: isTablet ? 100 : 80,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    marginTop: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  emptyIcon: {
    marginBottom: 20,
    opacity: 0.4,
  },
  emptyText: {
    fontSize: isTablet ? 20 : 18,
    fontWeight: "700",
    color: "#374151",
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  emptySubtext: {
    fontSize: 15,
    color: "#9CA3AF",
    textAlign: "center",
    paddingHorizontal: 40,
    lineHeight: 22,
    fontWeight: "500",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8F6F3",
  },
  loadingText: {
    marginTop: 20,
    fontSize: 16,
    color: "#6B7280",
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  // Responsive adjustments for desktop/tablet
  desktopContainer: {
    maxWidth: 1200,
    alignSelf: "center",
    width: "100%",
  },
  tabletContainer: {
    maxWidth: 768,
    alignSelf: "center",
    width: "100%",
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 28,
    maxWidth: isDesktop ? 600 : width - 40,
    width: "100%",
    maxHeight: height - 60,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.25,
    shadowRadius: 32,
    elevation: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#111827",
    letterSpacing: -0.3,
    flex: 1,
  },
  closeButton: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
  },
  modalBody: {
    maxHeight: height - 240,
  },
  // Skeleton loading styles
  skeletonCard: {
    backgroundColor: "#F9FAFB",
    overflow: "hidden",
  },
  skeletonHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  skeletonIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#E5E7EB",
  },
  skeletonGrowth: {
    width: 40,
    height: 20,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  skeletonValue: {
    width: 60,
    height: 28,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
    marginBottom: 6,
  },
  skeletonTitle: {
    width: 80,
    height: 14,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  skeletonSearchIcon: {
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
  },
  skeletonSearchInput: {
    flex: 1,
    height: 16,
    borderRadius: 4,
    backgroundColor: "#E5E7EB",
    marginLeft: 12,
  },
  skeletonFilterRow: {
    flexDirection: "row",
    gap: 6,
  },
  skeletonFilterTab: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#E5E7EB",
  },
  salonDetailsOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  salonDetailsContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    margin: 20,
    maxHeight: "80%",
    width: "90%",
    maxWidth: 500,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
  },
  salonDetailsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  salonDetailsTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
    flex: 1,
  },
  salonDetailsCloseButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
  },
  salonDetailsBody: {
    padding: 20,
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  badgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  detailSection: {
    gap: 8,
  },
  detailTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 8,
  },
  detailText: {
    fontSize: 14,
    color: "#6B7280",
    lineHeight: 20,
  },
  // Salon Details View Styles
  backButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
    marginRight: 16,
  },
  salonDetailsAction: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
  },
  salonInfo: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: isTablet ? 24 : 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  salonHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  salonNameContainer: {
    flex: 1,
  },
  salonName: {
    fontSize: isTablet ? 24 : 20,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 12,
  },
  badges: {
    flexDirection: "row",
    gap: 8,
  },
  salonBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  salonBadgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  detailsSection: {
    marginBottom: 20,
  },
  detailCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: isTablet ? 20 : 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  salonDetailTitle: {
    fontSize: isTablet ? 18 : 16,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 16,
  },
  detailContent: {
    gap: 12,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  detailLabel: {
    fontSize: isTablet ? 14 : 13,
    fontWeight: "600",
    color: "#6B7280",
    flex: 1,
  },
  detailValue: {
    fontSize: isTablet ? 14 : 13,
    fontWeight: "500",
    color: "#111827",
    flex: 2,
    textAlign: "right",
  },
  actionSection: {
    marginBottom: 20,
  },
  primaryActionButton: {
    backgroundColor: "#780115",
    borderRadius: 12,
    padding: isTablet ? 16 : 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 12,
    shadowColor: "#780115",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryActionText: {
    fontSize: isTablet ? 16 : 14,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  secondaryActions: {
    flexDirection: "row",
    gap: 12,
  },
  secondaryActionButton: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: isTablet ? 14 : 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  secondaryActionText: {
    fontSize: isTablet ? 14 : 12,
    fontWeight: "600",
    color: "#6B7280",
  },
});
